# Generated by Django 5.2.4 on 2025-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('enviada', 'Enviada')], default='emitida', max_length=10, verbose_name='Estado de envío'),
        ),
    ]
