# Generated by Django 5.2.4 on 2025-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Factura',
                'verbose_name_plural': 'Secuencias de Factura',
            },
        ),
    ]
